Open-CAS/standalone-linux-io-tracer

Makefile
=> Added empty test target for CI purposes

Makefile
=> Added uninstall target for iotrace

source/kernel/io_trace.c, source/kernel/procfs.c, source/kernel/trace_bdev.c
=> Static analysis fixes

source/kernel/io_trace.c
=> Further fixes after static code analysis

source/kernel/procfs.c
=> Updates permissions of procfs files

source/kernel/io_trace.c, source/kernel/procfs.c, source/kernel/procfs.h
Signed-off-by: Adam Rutkowski <adam.j.rutkowski@intel.com>
=> Allocate trace ring buffer on target cpu NUMA node

source/kernel/context.h, source/kernel/io_trace.c, source/kernel/procfs.c, source/kernel/trace_bdev.c, source/kernel/trace_bdev.h
Signed-off-by: Adam Rutkowski <adam.j.rutkowski@intel.com>
=> Cleanup procfs read/write handlers

doc/man/MAN.md, doc/man/iotrace.8
=> Adds short key to path cli switch

source/userspace/main.cpp
=> Calling iotrace without input now returns non-zero return code

CMakeLists.txt, Makefile
=> Updates building system

source/kernel/trace_bdev.c
=> Fixes kernel bug when adding device for tracing

source/kernel/context.h, source/kernel/io_trace.c, source/kernel/procfs.c
=> Notification of new events is sent only if there is a waiting thread. Whitespace fixes

source/includes/procfs_files.h, source/kernel/context.h, source/kernel/io_trace.c, source/kernel/io_trace.h, source/kernel/procfs.c, source/kernel/procfs.h, source/userspace/KernelRingTraceProducer.cpp, source/userspace/KernelRingTraceProducer.h, source/userspace/KernelTraceExecutor.cpp, source/userspace/KernelTraceExecutor.h
=> Uses wait queue instead of select when waiting on trace

source/kernel/main.c
=> Updates printing version by kernel module

source/kernel/trace_bio.c
=> Traces device id in IO completion

doc/IOTRACER.md
=> Adds detailed description of iotrace

source/kernel/config.h, source/kernel/trace_bio.c
=> Add write hints to traces

source/kernel/CMakeLists.txt, source/kernel/Makefile, source/kernel/context.h, source/kernel/io_trace.c, source/kernel/io_trace.h, source/kernel/main.c, source/kernel/trace_bio.c, source/kernel/trace_inode.c, source/kernel/trace_inode.h
=> Traces file name

source/userspace/InterfaceKernelTraceCreatingImpl.cpp, source/userspace/main.cpp
=> Moved exception handling to main(). Removed unneeded includes

CMakeLists.txt, Makefile, README.md, setup_dependencies.sh, source/userspace/CMakeLists.txt
=> Added setup_dependencies script to tracer repository

Makefile
=> Fixed cmake usage in Makefile

setup_dependencies.sh
=> Fixed invalid kernel headers package installation in setup script

setup_dependencies.sh
=> Added fedora to setup_dependencies script

source/kernel/config.h, source/kernel/trace_inode.c
=> Tracing filesystem events

source/kernel/trace_bio.c, source/kernel/trace_inode.c
=> Fixes tracing partition id

source/kernel/config.c, source/kernel/config.h
=> Updated config to allow compilation of 4.14 kernel

source/kernel/procfs.c
=> Prevents unloading module when tracing is active

source/kernel/config.h, source/kernel/trace_inode.c
=> Fixes kernel compilation error at 3.10.0-1062.4.3.el7

source/userspace/InterfaceKernelTraceCreatingImpl.cpp, source/userspace/KernelTraceExecutor.h
=> Waits for kernel module to be up and running

tests/conftest.py, tests/functional/test_sanity.py, tests/functional/test_stats.py, tests/utils/iotrace.py
=> Added tracing utils and trace start-stop test

tests/functional/test_integrity.py, tests/utils/fio.py
=> Add functional trace for iotrace + fio with verification

tests/functional/test_performance.py, tests/utils/fio.py
=> Add performance test for tracing during workload

source/kernel/io_trace.c, source/kernel/trace_bio.c, source/kernel/trace_inode.c
=> Change tracing to use zero copy interface

source/kernel/trace_inode.c
=> Fixed a bug in copying filenames from inode 

CMakeLists.txt
=> Added rpath to local installation

tests/README.md, tests/config/example_config.yml, tests/conftest.py, tests/dut_dependencies.txt, tests/dut_requirements.txt, tests/functional/test_fs.py, tests/utils/installer.py, tests/utils/iotrace.py
* Fixed example config
* Fixed module load/unload errors
* Updated tests README, fixed links
* Added type hints to iotrace util functions
* DUT is now cleaned up before and after tests, which includes removing all saved traces
=> General test fixes and enhancements

tests/functional/test_integrity.py, tests/utils/fio.py
=> Add data integrity test with multiple start/stop trace calls

tests/functional/test_fs.py
=> Tests now attempt to write to readonly files to verify permissions

tests/functional/test_performance.py
=> Updated acceptable performance drop value in tests

tests/utils/iotrace.py
Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>
=> Wrapper for trace stats command.

tests/api/iotrace_stats_parser.py
Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>
=> Wrapper class for parsed trace stats.

tests/conftest.py
Signed-off-by: Michal Rakowski <michal.rakowski@intel.com>
=> tests: remove redundant module instert/remove in conftest

tests/utils/iotrace.py
Signed-off-by: Michal Rakowski <michal.rakowski@intel.com>
=> Wrapper for get latency histogram command

source/kernel/config.h, source/kernel/io_trace.c, source/kernel/io_trace.h, source/kernel/trace_bdev.c, source/kernel/trace_bdev.h
=> Fix kernel panic during tracing on Centos 7

setup_dependencies.sh
=> Updates setup dependencies script

tests/utils/iotrace.py
=> Updates for new OCTF and its CLI changes

.pep8speaks.yml
Signed-off-by: Jan Musial <jan.musial@intel.com>
=> Update pep8 config

setup_dependencies.sh, source/kernel/config.h
=> Add Redhat/Centos 8 support

setup_dependencies.sh
=> Removed unnecessary dependencies for rpm in Ubuntu

tests/functional/test_stress.py
=> Add stress test for iotracer starting and stopping

NOTICE
=> Updated NOTICE

source/kernel/trace_bio.c, source/kernel/trace_inode.c
=> Change iotracer to supply inode creation date

setup_dependencies.sh
=> Fixes detecting RHEL8 distro in setup dependencies script

tests/api/iotrace_stats_parser.py, tests/functional/fs/test_fs_statistics.py
=> Update test_fs_statistics, taking into account test framework and octf

package.cmake
=> Remove .git folder from source_package

tests/conftest.py, tests/functional/fs/test_fs_operations.py, tests/functional/test_trace_io_events.py, tests/security/fuzzy/test_fuzzy.py, tests/security/test_fs.py, tests/security/test_integrity.py, tests/security/test_performance.py, tests/security/test_sanity.py, tests/utils/fio.py, tests/utils/git.py, tests/utils/installer.py, tests/utils/iotrace.py
Extend ***iotrace*** module
Modify `iotrace` module to be more useful.
Change some methods to be static.
Update usage of changed methods.
Add new methods.
Add parameters to existing methods.
Refactor code
=> Extend iotrace test API

tests/functional/fs/test_fs_statistics.py, tests/utils/iotrace.py
=> Minor fixes in *iotrace* module and test update after changes

tests/functional/test_trace_io_events.py, tests/security/test_fs.py
=> Fix tests after changes

package.cmake
=> Change string append to list append in cmake

tests/functional/test_trace_io_events.py
=> Fix test_io_events Read event handling

tests/conftest.py, tests/functional/test_package.py, tests/utils/installer.py
=> Add package installation test

tests/functional/test_package.py
=> Add source package installation test

tests/functional/test_trace_io_events.py
=> Add fua and flush flag test

tests/utils/installer.py
=> Fix check_if_ubuntu test util

tests/.gitignore, tests/__init__.py, tests/api/__init__.py, tests/conftest.py, tests/utils/dut.py, tests/utils/iotrace.py
=> [TESTS] Updates utilities

tests/conftest.py, tests/functional/test_package.py, tests/utils/installer.py, tests/utils/iotrace.py
=> Updates test framework

.gitignore, tests/functional/test_management.py, tests/utils/iotrace.py
=> Add trace removal test

tests/functional/test_trace_config.py, tests/utils/iotrace.py
=> Add tests for `iotrace -C` commands

source/kernel/trace_inode.c
=> Uses fsnotify only on compatible kernel version

setup_dependencies.sh
=> Adds one more methods to install Linux headers

tests/functional/test_summary.py
=> Add test for comparing trace summaries

source/userspace/InterfaceKernelTraceCreatingImpl.cpp
=> Add handling of default exceptions to iotracer

tests/functional/test_limits.py
=> Add test for verity tracing limits

source/kernel/trace_inode.c
Signed-off-by: Jan Musial <jan.musial@intel.com>
=> Replace strlen with safe sizeof

tests/api/iotrace_stats_parser.py
=> Fix import in fs statistics test

source/userspace/InterfaceKernelTraceCreatingImpl.cpp
Signed-off-by: Jan Musial <jan.musial@intel.com>
=> Fix potential nullptr in checkIntegerParameters

Makefile, package.cmake
=> Updates creation of source package

Makefile, package.cmake
=> Fixes again source package creation

Makefile, package.cmake
=> Updates main Makefile

tests/README.md, tests/dut_requirements.txt, tests/functional/test_management.py, tests/functional/test_package.py, tests/functional/test_trace_config.py, tests/functional/test_tracing.py, tests/utils/installer.py, tests/utils/iotrace.py
=> Fix test paths

CMakeLists.txt, install.cmake, source/userspace/CMakeLists.txt
=> Adds missing files in installation

source/userspace/InterfaceKernelTraceCreatingImpl.cpp, source/userspace/KernelTraceExecutor.cpp
=> Removes race condition when start tracing on ubuntu

source/userspace/KernelTraceExecutor.cpp
=> Fixes regression missing device description in trace file

package.cmake, setup_dependencies.sh
=> Updates script of setup dependencies

source/kernel/io_trace.c, source/kernel/trace_bdev.c
=> Fix deadlock during simultanteous remove and add device

source/kernel/trace_inode.c
=> Fix unsafe deletion in hashtable

source/kernel/trace_bdev.c, tests/security/fuzzy/test_fuzzy.py
=> Fix race condition between adding bdev and attaching client

tests/functional/test_management.py, tests/functional/test_package.py
Fix removal of old packages in package installation test
=> Update remove trace test timings

source/kernel/config.h
=> Fix detection of lookup_bdev for Ubuntu releases

source/kernel/trace_inode.c
Inode tracer is a per CPU resource, while FSM is global. During shutdown
the inode in group may be freed on one CPU, while FSM is still executing
on another. This patch should fix this issue.
Fixes #254
=> Changed group private structure to hold fsm instead of inode tracer

source/kernel/procfs.c
=> Fix static analysis tool sizeof warning

source/kernel/context.h, source/kernel/io_trace.c, source/kernel/io_trace.h, source/kernel/trace_bdev.c, source/kernel/trace_bdev.h
=> Merge client and bdev mutex into one

source/kernel/config.h, source/kernel/io_trace.c, source/kernel/io_trace.h, source/kernel/trace_bdev.c, source/kernel/trace_bio.c, source/userspace/InterfaceKernelTraceCreatingImpl.cpp
Includes tracing device model and handling of split BIOs.
Fixes #242
=> Implement v1 version of trace files

source/kernel/CMakeLists.txt, source/kernel/configure.d/1_proc_fs.conf, source/kernel/procfs.c, source/kernel/trace_inode.c
=> Kernel 5.7 support

setup_dependencies.sh
=> Add debian support

source/kernel/trace_bdev.c
=> Fix preemption handling

source/kernel/trace_inode.c
=> Fix potential null pointer dereference

README.md, setup_dependencies.sh, source/iotrace/configure.d/1_page.conf, source/iotrace/iotrace.bpf.defs.h
=> BPF support for older kernels
